name: educational_cms
description: Educational Content Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.3.1
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1

  # State Management
  provider: ^6.0.5
  flutter_bloc: ^9.1.1

  # Network & API
  http: ^1.1.0
  dio: ^5.3.2
  connectivity_plus: ^7.0.0

  # Storage & Preferences
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1

  # Firebase (compatible versions)
  
  cloud_firestore: ^6.0.1
  firebase_analytics: ^12.0.1
  firebase_messaging: ^16.0.1
  firebase_crashlytics: ^5.0.1

  # File Handling
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  open_file: ^3.3.2
  url_launcher: ^6.1.14
  permission_handler: ^12.0.1

  # Forms & Validation
  form_field_validator: ^1.1.0

  # Date & Time
  intl: ^0.20.2
  timeago: ^3.5.0

  # Utils
  logger: ^2.0.2
  uuid: ^4.5.1

  # PDF & Documents
  pdf: ^3.10.4
  printing: ^5.11.0
  syncfusion_flutter_pdfviewer: ^31.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
